variable "region" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "public_subnet_az" {}
variable "jenkins_key_name" {}
variable "jenkins_ami_id" {}
variable "jenkins_instance_type" {}
variable "jenkins_volume_size" {}
variable "jenkins_volume_type" {}
